#pragma once

// Water placement data types - shared between preprocessing tools and runtime engine
// These types are used to store pre-computed water data from erosion simulation

#include <glm/glm.hpp>
#include <vector>
#include <cstdint>

// A river represented as a spline with varying width
struct RiverSpline {
    std::vector<glm::vec3> controlPoints;  // World-space positions (x, height, z)
    std::vector<float> widths;             // Width at each control point (based on flow)
    float totalFlow = 0.0f;                // Total accumulated flow for this river
};

// A detected lake/pond
struct Lake {
    glm::vec2 position;                    // Center position in world XZ
    float waterLevel;                      // Surface height in world Y
    float radius;                          // Approximate radius
    float area;                            // Surface area in world units squared
    float depth;                           // Maximum depth
    std::vector<glm::vec2> shoreline;      // Detailed shoreline points (optional)
};

// Complete water placement data generated by erosion simulation
struct WaterPlacementData {
    std::vector<RiverSpline> rivers;
    std::vector<Lake> lakes;
    float seaLevel = 0.0f;                 // Sea level threshold

    // Flow accumulation data (normalized 0-1, can be used as texture)
    std::vector<float> flowAccumulation;
    // D8 flow direction: 0-7 for 8 directions (E,SE,S,SW,W,NW,N,NE), -1 for outlet
    std::vector<int8_t> flowDirection;
    uint32_t flowMapWidth = 0;
    uint32_t flowMapHeight = 0;

    // Statistics
    uint32_t numDropletsSimulated = 0;
    float maxFlowValue = 0.0f;
};
