// Auto-generated by shader_reflect tool
// DO NOT EDIT MANUALLY - this file is generated from SPIR-V shaders

#pragma once

#include <glm/glm.hpp>

// Binding: 1, Set: 0
struct AtmosphereUniforms {
    AtmosphereParams params;
    glm::vec4 sunDirection;
    glm::vec4 cameraPosition;
    float padding[2];
};

// Binding: 7, Set: 0
struct DisplacementRegion {
    glm::vec4 regionCenterAndSize;
};

// Binding: 2, Set: 0
struct FroxelUniforms {
    glm::vec4 invViewProj;
    glm::vec4 prevViewProj;
    glm::vec4 cascadeViewProj[4];
    glm::vec4 cascadeSplits;
    glm::vec4 cameraPosition;
    glm::vec4 sunDirection;
    glm::vec4 sunColor;
    glm::vec4 fogParams;
    glm::vec4 layerParams;
    glm::vec4 gridParams;
    glm::vec4 shadowParams;
};

// Binding: 2, Set: 0
struct GrassUniforms {
    glm::vec4 cameraPosition;
    glm::vec4 frustumPlanes[6];
    glm::vec4 displacementRegion;
    float maxDrawDistance;
    float lodTransitionStart;
    float lodTransitionEnd;
    float terrainSize;
    float terrainHeightScale;
    float padding[3];
};

// Binding: 2, Set: 0
struct HistogramParams {
    float minLogLum;
    float maxLogLum;
    float invLogLumRange;
    uint32_t pixelCount;
};

// Binding: 3, Set: 0
struct LeafUniforms {
    glm::vec4 cameraPosition;
    glm::vec4 frustumPlanes[6];
    glm::vec4 playerPosition;
    glm::vec4 playerVelocity;
    glm::vec4 spawnRegionMin;
    glm::vec4 spawnRegionMax;
    glm::vec4 confettiSpawnPos;
    float groundLevel;
    float deltaTime;
    float time;
    float maxDrawDistance;
    float disruptionRadius;
    float disruptionStrength;
    float gustThreshold;
    float targetFallingCount;
    float targetGroundedCount;
    float confettiSpawnCount;
    float confettiVelocity;
    float terrainSize;
    float terrainHeightScale;
    float padding[1];
};

// Binding: 1, Set: 0
struct PostProcessUniforms {
    float exposure;
    float bloomThreshold;
    float bloomIntensity;
    float autoExposure;
    float previousExposure;
    float deltaTime;
    float adaptationSpeed;
    float bloomRadius;
    glm::vec2 sunScreenPos;
    float godRayIntensity;
    float godRayDecay;
    float froxelEnabled;
    float froxelFarPlane;
    float froxelDepthDist;
    float nearPlane;
    float farPlane;
    float sceneIlluminance;
    float padding2;
    float padding3;
};

// Binding: 4, Set: 0
struct TerrainUniforms {
    glm::vec4 viewMatrix;
    glm::vec4 projMatrix;
    glm::vec4 viewProjMatrix;
    glm::vec4 frustumPlanes[6];
    glm::vec4 cameraPosition;
    glm::vec4 terrainParams;
    glm::vec4 lodParams;
    glm::vec2 screenSize;
    float lodFactor;
    float padding;
};

// Binding: 0, Set: 0
struct UniformBufferObject {
    glm::vec4 model;
    glm::vec4 view;
    glm::vec4 proj;
    glm::vec4 cascadeViewProj[4];
    glm::vec4 cascadeSplits;
    glm::vec4 sunDirection;
    glm::vec4 moonDirection;
    glm::vec4 sunColor;
    glm::vec4 moonColor;
    glm::vec4 ambientColor;
    glm::vec4 cameraPosition;
    glm::vec4 pointLightPosition;
    glm::vec4 pointLightColor;
    glm::vec4 windDirectionAndSpeed;
    float timeOfDay;
    float shadowMapSize;
    float debugCascades;
    float julianDay;
};

// Binding: 3, Set: 0
struct WeatherUniforms {
    glm::vec4 cameraPosition;
    glm::vec4 frustumPlanes[6];
    glm::vec4 windDirectionStrength;
    glm::vec4 gravity;
    glm::vec4 spawnRegion;
    float spawnHeight;
    float groundLevel;
    float particleDensity;
    float maxDrawDistance;
    float time;
    float deltaTime;
    uint32_t weatherType;
    float intensity;
    float nearZoneRadius;
    float padding[3];
};

// Binding: 3, Set: 0
struct WindUniforms {
    glm::vec4 windDirectionAndStrength;
    glm::vec4 windParams;
};

